spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
logging:
  level:
    org:
      hibernate:
        type: trace
        
leeda:
  user:
    name: 이다현천재님-bus
